-- 09_products_data.sql
-- Load mock product data from JSON file
-- Generates random embeddings for testing (replace with real embeddings in production)

-- Helper function to generate random embeddings for testing
CREATE OR REPLACE FUNCTION products.generate_random_embedding(dim INT)
RETURNS vector AS $$
DECLARE
    embedding_array FLOAT[];
    i INT;
BEGIN
    embedding_array := ARRAY[]::FLOAT[];
    FOR i IN 1..dim LOOP
        embedding_array := array_append(embedding_array, (random() * 2 - 1)::FLOAT);
    END LOOP;
    RETURN embedding_array::vector;
END;
$$ LANGUAGE plpgsql;

-- Insert product data
-- Note: In production, replace generate_random_embedding() with real embeddings from OpenAI ada-002 or similar
INSERT INTO products.items (name, description, brand, category, subcategory, tags, price, rating, review_count, stock_quantity, in_stock, featured, attributes, description_embedding) VALUES
('Sony WH-1000XM5 Wireless Headphones', 'Industry-leading noise cancellation with Auto NC Optimizer automatically detects your environment and adjusts sound accordingly. Crystal clear hands-free calling with 4 beamforming microphones, precise voice pickup, and advanced audio signal processing. Up to 30-hour battery life with quick charging - 3 minutes charge provides 3 hours playback. Multipoint connection allows seamless switching between two Bluetooth devices. Speak-to-Chat automatically pauses music when you start a conversation. Ultra-comfortable design with soft fit leather and silent joints for all-day wear.', 'Sony', 'Electronics', 'Headphones', ARRAY['wireless', 'bluetooth', 'noise-cancellation', 'premium', 'over-ear'], 349.99, 4.8, 2847, 156, true, true, '{"color": "Black", "connectivity": "Bluetooth 5.2", "battery_life_hours": 30, "weight_grams": 250, "driver_size_mm": 30}'::jsonb, products.generate_random_embedding(1536)),

('Apple AirPods Pro 2nd Generation', 'Active Noise Cancellation reduces unwanted background noise. Adaptive Transparency lets outside sounds in while reducing loud environmental noise. Personalized Spatial Audio with dynamic head tracking places sound all around you. Touch control lets you swipe to adjust volume and press to control playback. Up to 6 hours of listening time with ANC enabled. MagSafe Charging Case provides multiple additional charges for 30 hours total listening time. Sweat and water resistant IPX4 rated earbuds.', 'Apple', 'Electronics', 'Headphones', ARRAY['wireless', 'bluetooth', 'noise-cancellation', 'premium', 'earbuds', 'spatial-audio'], 249.99, 4.7, 5623, 342, true, true, '{"color": "White", "connectivity": "Bluetooth 5.3", "battery_life_hours": 6, "weight_grams": 5.3, "chip": "H2"}'::jsonb, products.generate_random_embedding(1536)),

('JBL Tune 510BT Budget Wireless Headphones', 'Powerful JBL Pure Bass Sound delivers an experience you can feel. Wireless Bluetooth 5.0 streaming lets you enjoy music without tangled cables. Foldable design with soft padded headband ensures comfortable listening on the go. 40-hour battery life keeps the music playing for days. Quick charge feature gives 2 hours playback from just 5 minutes charging. Lightweight and comfortable for extended wear during commutes or workouts. Multi-point connection to switch between devices.', 'JBL', 'Electronics', 'Headphones', ARRAY['wireless', 'bluetooth', 'budget', 'on-ear', 'foldable'], 49.99, 4.3, 8934, 523, true, false, '{"color": "Blue", "connectivity": "Bluetooth 5.0", "battery_life_hours": 40, "weight_grams": 160, "driver_size_mm": 32}'::jsonb, products.generate_random_embedding(1536)),

('Logitech MX Master 3S Wireless Mouse', 'Advanced 8K DPI optical sensor tracks on virtually any surface including glass. MagSpeed electromagnetic scrolling feels precise and fast - scroll 1000 lines per second. Quiet clicks reduce noise by 90% compared to previous generation. Ergonomic shape supports your hand for all-day comfort and productivity. Connect via Bluetooth or USB receiver. Works with up to three devices and switches between them with a button press. USB-C quick charging - 1 minute provides 3 hours of use. Compatible with macOS, Windows, Linux, Chrome OS, and iPadOS.', 'Logitech', 'Electronics', 'Mice', ARRAY['wireless', 'ergonomic', 'productivity', 'premium', 'bluetooth'], 99.99, 4.9, 3421, 89, true, true, '{"color": "Graphite", "connectivity": "Bluetooth, USB Receiver", "battery_life_days": 70, "dpi": 8000, "buttons": 7}'::jsonb, products.generate_random_embedding(1536)),

('Razer DeathAdder V3 Pro Gaming Mouse', 'Focus Pro 30K optical sensor delivers best-in-class precision with 30000 DPI tracking. Ultra-lightweight 63g design for lightning-fast flick shots and reduced fatigue during marathon gaming sessions. Optical mouse switches Gen-3 with 90-million click lifecycle and zero double-click issues. HyperSpeed Wireless technology provides lag-free performance competitive with wired mice. 90 hours battery life on single charge. Ergonomic right-handed design refined over 15 years of evolution. 5 programmable buttons with on-board memory. Compatible with Razer Synapse for advanced customization.', 'Razer', 'Electronics', 'Mice', ARRAY['gaming', 'wireless', 'esports', 'lightweight', 'ergonomic'], 149.99, 4.8, 1876, 67, true, true, '{"color": "Black", "connectivity": "HyperSpeed Wireless, USB-C", "battery_life_hours": 90, "dpi": 30000, "weight_grams": 63}'::jsonb, products.generate_random_embedding(1536)),

('Amazon Basics Wired USB Mouse', 'Simple and reliable wired optical mouse for everyday computing tasks. Smooth optical tracking works on most surfaces. Three-button design with scroll wheel covers essential functions. USB plug-and-play connection requires no software installation. Ambidextrous design suits both left and right-handed users. Compact size fits well in laptop bags for travel. High-resolution optical sensor provides responsive cursor control. Affordable replacement for broken or lost mice.', 'Amazon Basics', 'Electronics', 'Mice', ARRAY['wired', 'budget', 'office', 'basic', 'ambidextrous'], 8.99, 4.1, 45678, 1234, true, false, '{"color": "Black", "connectivity": "USB Wired", "dpi": 1000, "buttons": 3, "cable_length_m": 1.5}'::jsonb, products.generate_random_embedding(1536)),

('Keychron Q1 Pro Mechanical Keyboard', 'Premium QMK/VIA compatible wireless mechanical keyboard with full aluminum CNC-machined body. South-facing RGB LEDs provide per-key backlighting with multiple effects. Hot-swappable PCB supports 3-pin and 5-pin mechanical switches without soldering. Gasket mount design with silicone dampening reduces typing noise and provides satisfying feedback. Triple connectivity via Bluetooth 5.1, 2.4GHz wireless, or USB-C wired mode. 4000mAh battery delivers up to 300 hours use with backlighting off. Pre-lubed Gateron G Pro switches included. Rotary encoder knob for volume control. Mac and Windows compatible keycap sets included.', 'Keychron', 'Electronics', 'Keyboards', ARRAY['mechanical', 'wireless', 'bluetooth', 'premium', 'hot-swap', 'RGB', 'programmable'], 199.99, 4.7, 892, 34, true, true, '{"color": "Space Gray", "connectivity": "Bluetooth 5.1, 2.4GHz, USB-C", "layout": "75%", "switches": "Gateron G Pro Red", "keycaps": "Double-shot PBT"}'::jsonb, products.generate_random_embedding(1536)),

('Logitech K380 Multi-Device Bluetooth Keyboard', 'Compact wireless keyboard connects up to three devices simultaneously and switches between them with dedicated Easy-Switch buttons. Familiar comfortable typing experience with well-spaced round keys. Compatible with Windows, macOS, Chrome OS, Android, iOS, and iPadOS. Two AAA batteries provide up to 2 years of power. Slim portable design weighs only 423g and slips easily into bags. Quiet typing suitable for shared workspaces and libraries. Line of colors available to match your style. Automatic sleep mode conserves battery when not in use.', 'Logitech', 'Electronics', 'Keyboards', ARRAY['bluetooth', 'wireless', 'compact', 'multi-device', 'budget', 'portable'], 39.99, 4.6, 23456, 567, true, false, '{"color": "Rose", "connectivity": "Bluetooth", "layout": "Compact", "battery_type": "2x AAA", "battery_life_months": 24}'::jsonb, products.generate_random_embedding(1536)),

('Dell UltraSharp U2723QE 27-inch 4K Monitor', '27-inch 4K UHD IPS Black panel delivers exceptional contrast with 2000:1 ratio. 100% sRGB, 98% DCI-P3 color coverage factory calibrated for Delta E < 2 accuracy. USB-C hub monitor with 90W power delivery charges laptops while transferring video and data over single cable. Built-in KVM switch lets you control two computers with one keyboard and mouse. Height, tilt, swivel, and pivot adjustability for ergonomic positioning. Low blue light hardware solution reduces eye strain without color distortion. Picture-by-Picture and Picture-in-Picture modes for multitasking. VESA DisplayHDR 400 certified.', 'Dell', 'Electronics', 'Monitors', ARRAY['4K', 'USB-C', 'IPS', 'professional', 'color-accurate', 'hub'], 799.99, 4.8, 1234, 23, true, true, '{"screen_size_inches": 27, "resolution": "3840x2160", "panel_type": "IPS Black", "refresh_rate_hz": 60, "response_time_ms": 5}'::jsonb, products.generate_random_embedding(1536)),

('Samsung Odyssey G7 32-inch Curved Gaming Monitor', '1000R curved display immerses you in the action with curvature matching human eye for reduced strain. WQHD 2560x1440 resolution delivers stunning detail in games. 240Hz refresh rate and 1ms response time eliminate motion blur and ghosting. NVIDIA G-SYNC and AMD FreeSync Premium Pro compatible for tear-free gaming. QLED quantum dot technology produces 125% sRGB color gamut. 600 nits peak brightness with HDR600 support. CoreSync lighting on back syncs with on-screen content. Infinity Core Lighting creates ambient glow behind monitor. Height, tilt, and swivel adjustable stand included.', 'Samsung', 'Electronics', 'Monitors', ARRAY['gaming', 'curved', '240Hz', 'QLED', 'G-SYNC', 'HDR'], 699.99, 4.6, 2567, 45, true, true, '{"screen_size_inches": 32, "resolution": "2560x1440", "panel_type": "VA", "refresh_rate_hz": 240, "response_time_ms": 1}'::jsonb, products.generate_random_embedding(1536)),

('ASUS ProArt PA279CRV 27-inch Creator Monitor', 'Professional monitor designed for content creators with 99% DCI-P3 and 99% Adobe RGB color coverage. Calman Verified factory calibration ensures Delta E < 2 out of the box. 27-inch 4K UHD IPS panel with wide 178-degree viewing angles. USB-C with 96W power delivery and daisy chain capability. Built-in colorimeter holder for hardware calibration workflows. ProArt Palette software enables custom color profiles. HDR10 support for high dynamic range content preview. Low blue light and flicker-free certified for comfortable long editing sessions. Ergonomic stand with height, tilt, swivel, and 90-degree pivot rotation.', 'ASUS', 'Electronics', 'Monitors', ARRAY['4K', 'professional', 'color-accurate', 'USB-C', 'creator', 'calibrated'], 899.99, 4.7, 456, 12, true, false, '{"screen_size_inches": 27, "resolution": "3840x2160", "panel_type": "IPS", "refresh_rate_hz": 60, "color_accuracy_delta_e": 2}'::jsonb, products.generate_random_embedding(1536)),

('Sony Alpha a7 IV Full-Frame Mirrorless Camera', '33-megapixel full-frame Exmor R CMOS sensor captures incredible detail in photos and 4K 60p video. Advanced Real-time Eye AF tracks human, animal, and bird eyes with remarkable accuracy. 10fps continuous shooting with AF/AE tracking captures decisive moments. 5-axis in-body image stabilization provides up to 5.5 stops of shake compensation. 759 phase-detection AF points cover 94% of image area. 4K 60p 10-bit 4:2:2 internal recording for professional video production. Creative Look profiles provide in-camera color grading. Breathing compensation maintains consistent angle of view during focus pulls. Dual card slots support CFexpress Type A and SD cards. Weather-sealed magnesium alloy body.', 'Sony', 'Electronics', 'Cameras', ARRAY['mirrorless', 'full-frame', '4K', 'professional', 'autofocus', 'video'], 2499.99, 4.9, 1876, 15, true, true, '{"sensor_type": "Full-Frame", "megapixels": 33, "video_resolution": "4K 60p", "iso_range": "100-51200", "weight_grams": 658}'::jsonb, products.generate_random_embedding(1536)),

('Canon EOS R50 Entry-Level Mirrorless Camera', 'Compact and lightweight mirrorless camera perfect for beginners and content creators. 24.2MP APS-C CMOS sensor delivers beautiful images and 4K 30p video. Dual Pixel CMOS AF II with intelligent subject detection tracks people, animals, and vehicles. Advanced A+ scene intelligent auto mode handles tricky lighting situations. Vertical video support for social media content creation. Built-in Wi-Fi and Bluetooth for easy smartphone connectivity. Vari-angle touchscreen LCD for selfies and vlogging. Creative Assist makes it easy to adjust background blur, brightness, and color. Electronic viewfinder with 2.36 million dots. Compatible with extensive RF and EF lens lineup via adapter.', 'Canon', 'Electronics', 'Cameras', ARRAY['mirrorless', 'beginner', '4K', 'vlogging', 'compact', 'touchscreen'], 679.99, 4.5, 892, 78, true, false, '{"sensor_type": "APS-C", "megapixels": 24.2, "video_resolution": "4K 30p", "iso_range": "100-32000", "weight_grams": 376}'::jsonb, products.generate_random_embedding(1536)),

('GoPro HERO12 Black Action Camera', 'Capture incredible 5.3K60 video and 27MP photos in any adventure. Revolutionary HyperSmooth 6.0 stabilization with 360-degree Horizon Lock keeps footage level even during extreme action. Waterproof to 33ft without housing for underwater footage. HDR video in 5.3K and 4K captures highlight and shadow detail. 8:7 aspect ratio sensor provides maximum versatility for cropping to any platform. Bluetooth audio connectivity for wireless microphone support. GP-Log for maximum flexibility in color grading. Emmy Award-winning stabilization technology. Enduro battery rated for extended performance in cold conditions. Touch rear screen and front screen for easy framing.', 'GoPro', 'Electronics', 'Cameras', ARRAY['action-camera', 'waterproof', '4K', 'stabilization', 'compact', 'adventure'], 399.99, 4.6, 3456, 234, true, true, '{"video_resolution": "5.3K 60fps", "megapixels": 27, "waterproof_depth_ft": 33, "weight_grams": 154, "stabilization": "HyperSmooth 6.0"}'::jsonb, products.generate_random_embedding(1536)),

('Anker PowerCore 26800mAh Portable Charger', 'Massive 26800mAh capacity charges iPhone 14 over 6 times or Galaxy S23 nearly 5 times. High-speed charging with PowerIQ and VoltageBoost delivers device-optimized charging up to 3A. Three USB-A output ports charge three devices simultaneously. Recharges in approximately 6 hours with dual Micro USB input. MultiProtect safety system provides surge protection, short circuit prevention, and temperature control. LED power indicator displays remaining capacity. Premium matte finish resists fingerprints and scratches. TSA-approved for carry-on luggage. Compact size relative to enormous capacity. Includes travel pouch and Micro USB cable.', 'Anker', 'Electronics', 'Accessories', ARRAY['power-bank', 'portable', 'USB', 'travel', 'high-capacity'], 59.99, 4.7, 67890, 892, true, false, '{"capacity_mah": 26800, "output_ports": 3, "output_amps": 3, "weight_grams": 496, "dimensions_mm": "180x80x24"}'::jsonb, products.generate_random_embedding(1536)),

('Herman Miller Aeron Ergonomic Office Chair', 'Iconic ergonomic office chair designed for all-day comfort and support. Patented 8Z Pellicle suspension distributes weight evenly and keeps you cool. PostureFit SL supports the natural S-shape of your spine from sacrum to lumbar. Adjustable armrests, seat height, seat depth, and tilt tension customize fit to your body. Three sizes available to match your height and weight. Breathable mesh back and seat eliminate pressure points and heat buildup. Forward tilt option for active sitting and focus work. 12-year warranty demonstrates commitment to quality and durability. Made with ocean-bound plastic in partnership with NextWave Plastics. BIFMA certified for commercial use.', 'Herman Miller', 'Home & Garden', 'Furniture', ARRAY['ergonomic', 'office', 'premium', 'adjustable', 'mesh', 'sustainable'], 1395.00, 4.8, 4567, 34, true, true, '{"color": "Graphite", "size": "B (Medium)", "material": "8Z Pellicle Mesh", "warranty_years": 12, "max_weight_lbs": 350}'::jsonb, products.generate_random_embedding(1536)),

('IKEA MARKUS Office Chair', 'Popular budget-friendly office chair with built-in lumbar support and high back. Mesh back keeps you cool and comfortable during long work sessions. 10-year warranty provides peace of mind. Height adjustable seat fits various desk configurations. Tilt and lock function lets you lean back and lock position. Armrests provide support and can be removed if preferred. Safety casters automatically brake when rising and roll smoothly on hard floors. Assembly required with clear instructions included. Available in multiple colors to match your workspace. Tested and approved for commercial use.', 'IKEA', 'Home & Garden', 'Furniture', ARRAY['office', 'budget', 'ergonomic', 'mesh', 'adjustable'], 229.00, 4.4, 12345, 256, true, false, '{"color": "Glose Black", "material": "Mesh Back, Fabric Seat", "warranty_years": 10, "max_weight_lbs": 242, "seat_height_range_inches": "17.75-22"}'::jsonb, products.generate_random_embedding(1536)),

('Secretlab TITAN Evo Gaming Chair', 'Premium gaming chair engineered for extended play sessions. 4-way L-ADAPT lumbar support system adjusts to your spine. Cold-cure foam padding maintains shape and support after years of use. SoftWeave Plus fabric breathes and feels soft while being durable and easy to clean. Magnetic memory foam head pillow with cooling gel provides neck support. Multi-tilt mechanism with lockable recline up to 165 degrees. Full-metal 4D armrests adjust in four directions and hold position firmly. Pebble seat base reduces pressure under thighs. XL versions available for taller users. 5-year extended warranty included. Approved by esports professionals worldwide.', 'Secretlab', 'Home & Garden', 'Furniture', ARRAY['gaming', 'ergonomic', 'premium', 'adjustable', 'esports'], 519.00, 4.7, 8901, 67, true, true, '{"color": "Stealth", "material": "SoftWeave Plus Fabric", "warranty_years": 5, "max_weight_lbs": 285, "recline_degrees": 165}'::jsonb, products.generate_random_embedding(1536)),

('Ninja Foodi 6-in-1 Smart XL Indoor Grill', 'Smoke-free indoor grilling with cyclonic grilling technology circulates hot air around food for searing and crisping. Six cooking functions: grill, air crisp, roast, bake, broil, and dehydrate. Smart Cook System with Foodi Smart Thermometer monitors internal temperature and adjusts heat for perfect results. XL capacity fits 6 steaks, 24 hot dogs, or mains and sides at once. 500F high-heat searing for char-grilled marks and flavor. Splatter shield reduces mess and smoke. Ceramic-coated grill grate and crisper basket are nonstick and dishwasher safe. Digital control panel displays time, temperature, and food type. Recipe guide includes over 50 chef-inspired recipes.', 'Ninja', 'Home & Garden', 'Kitchen', ARRAY['indoor-grill', 'air-fryer', 'smart', 'smokeless', 'multi-function'], 279.99, 4.6, 23456, 189, true, true, '{"capacity_quarts": 4, "wattage": 1760, "functions": 6, "dishwasher_safe": true, "dimensions_inches": "17.1x15.6x10.6"}'::jsonb, products.generate_random_embedding(1536)),

('Instant Pot Duo Plus 6-Quart Pressure Cooker', '9-in-1 multi-use programmable pressure cooker replaces slow cooker, rice cooker, steamer, saute pan, yogurt maker, warmer, sterilizer, and sous vide. Easy-to-use single-touch programs for soup, meat, beans, rice, porridge, steam, and more. Advanced steam release technology prevents splashing. Stainless steel inner pot is dishwasher safe and scratch resistant. Cook up to 70% faster than traditional methods. Safety features include overheat protection, safety lock, and 10+ safety mechanisms. Free companion app with over 1000 tested recipes. 6-quart capacity feeds up to 6 people. Quiet steam release compared to older models.', 'Instant Pot', 'Home & Garden', 'Kitchen', ARRAY['pressure-cooker', 'multi-function', 'programmable', 'smart', 'time-saving'], 89.99, 4.7, 156789, 567, true, false, '{"capacity_quarts": 6, "wattage": 1000, "functions": 9, "dishwasher_safe": true, "pressure_settings": 2}'::jsonb, products.generate_random_embedding(1536)),

('West Elm Mid-Century Modern Coffee Table', 'Iconic mid-century modern design features splayed tapered legs and clean lines. Solid wood legs in walnut or acacia finish provide stability and natural beauty. Lacquered wood top resists scratches and stains. Lower shelf provides additional storage and display space. Fair Trade Certified factory ensures ethical manufacturing. GREENGUARD Gold certified for low chemical emissions. Assembly required - includes all hardware and instructions. 42-inch length works well with standard sofas. Protected feet prevent floor scratches. Pairs beautifully with West Elm mid-century sofa collection.', 'West Elm', 'Home & Garden', 'Furniture', ARRAY['mid-century', 'modern', 'sustainable', 'living-room', 'wood'], 599.00, 4.3, 2341, 45, true, false, '{"material": "Solid Wood", "finish": "Walnut", "dimensions_inches": "42x20x18", "weight_lbs": 45, "assembly_required": true}'::jsonb, products.generate_random_embedding(1536)),

('Patagonia Better Sweater Fleece Jacket', 'Versatile fleece jacket made from 100% recycled polyester fleece. Sweater-knit face with fleece interior provides warmth without bulk. Fair Trade Certified sewn for worker welfare. Zippered handwarmer pockets and left-chest pocket secure essentials. Flat-seam construction reduces bulk and chafing. Internal collar and wind flap add comfort and protection. Can be layered as midlayer or worn alone. Classic fit allows room for layering. Available in men''s and women''s cuts. Machine washable for easy care. Part of Patagonia''s commitment to environmental responsibility.', 'Patagonia', 'Clothing', 'Jackets', ARRAY['fleece', 'sustainable', 'outdoor', 'layering', 'recycled'], 139.00, 4.8, 5678, 234, true, true, '{"color": "New Navy", "material": "100% Recycled Polyester", "fit": "Classic", "weight_oz": 15.4, "pockets": 3}'::jsonb, products.generate_random_embedding(1536)),

('Nike Air Zoom Pegasus 40 Running Shoes', 'Legendary running shoe returns with responsive cushioning for everyday runs. Zoom Air unit in forefoot provides snappy energy return. Nike React foam midsole offers soft yet responsive cushioning mile after mile. Engineered mesh upper delivers breathable comfort and secure fit. Midfoot webbing integrates with laces for adjustable lockdown. Waffle-inspired outsole pattern provides traction on various surfaces. 10mm heel-to-toe offset suits neutral runners. Reflective elements enhance visibility in low light. Tongue securely attaches to inner sleeve to prevent bunching. Weighs approximately 10.2 oz for men''s size 10.', 'Nike', 'Clothing', 'Shoes', ARRAY['running', 'athletic', 'cushioned', 'breathable', 'everyday'], 130.00, 4.6, 34567, 456, true, true, '{"color": "Black/White", "heel_drop_mm": 10, "weight_oz": 10.2, "cushioning": "Nike React + Zoom Air", "terrain": "Road"}'::jsonb, products.generate_random_embedding(1536)),

('Levi''s 501 Original Fit Jeans', 'The original blue jean since 1873 - authentic, genuine Levi''s. Straight leg with button fly and classic five-pocket styling. Sits at waist with regular fit through thigh. Iconic leather patch and arcuate stitching on back pockets. Pre-shrunk cotton ensures consistent fit wash after wash. Available in variety of washes from light to dark. Signature sturdy construction built to last for years. Cottonized hemp option available for sustainable choice. Versatile style works dressed up or down. True American classic that never goes out of fashion.', 'Levi''s', 'Clothing', 'Pants', ARRAY['denim', 'jeans', 'classic', 'casual', 'American'], 69.50, 4.5, 89012, 789, true, false, '{"color": "Medium Stonewash", "fit": "Original", "material": "100% Cotton", "rise": "Regular", "closure": "Button Fly"}'::jsonb, products.generate_random_embedding(1536)),

('Uniqlo Heattech Ultra Warm Crew Neck T-Shirt', 'Advanced thermal technology generates heat from body moisture. 2.25 times warmer than standard Heattech for extreme cold conditions. Soft and stretchy fabric moves with your body. Smooth texture comfortable as base layer under any clothing. Anti-odor technology controls bacteria growth. Moisture-wicking keeps skin dry during activity. Flatlock seams reduce irritation and bulk. Tag-free label for comfort against skin. Machine washable and quick drying. Perfect for outdoor winter activities or as everyday warmth layer.', 'Uniqlo', 'Clothing', 'T-Shirts', ARRAY['thermal', 'base-layer', 'winter', 'moisture-wicking', 'comfortable'], 24.90, 4.4, 12345, 567, true, false, '{"color": "Black", "material": "40% Acrylic, 32% Rayon, 21% Polyester, 7% Spandex", "warmth_level": "Ultra Warm", "fit": "Slim", "care": "Machine Wash"}'::jsonb, products.generate_random_embedding(1536)),

('Arc''teryx Beta AR Gore-Tex Jacket', 'All-round waterproof hardshell jacket for severe weather conditions. Gore-Tex Pro provides legendary waterproof and breathable protection. Helmet-compatible StormHood adjusts with single hand pull. Pit zippers provide ventilation during high-output activities. WaterTight external zippers keep pockets dry. Articulated elbows and gusseted underarms allow full range of motion. Laminated brim sheds water away from face. Dropped back hem and adjustable drawcord seal out weather. Regular fit allows layering with insulation. Weight of just 470g despite heavy-duty protection. Backed by Arc''teryx lifetime warranty.', 'Arc''teryx', 'Clothing', 'Jackets', ARRAY['waterproof', 'Gore-Tex', 'outdoor', 'technical', 'premium'], 599.00, 4.9, 1234, 23, true, true, '{"color": "Black", "material": "Gore-Tex Pro", "waterproof_rating": "28000mm", "breathability": "25000g", "weight_grams": 470}'::jsonb, products.generate_random_embedding(1536)),

('Allbirds Tree Runners Sustainable Sneakers', 'Lightweight and breathable sneakers made from eucalyptus tree fiber. Carbon neutral product with offset emissions. Naturally soft and breathable material keeps feet cool. Bio-based SweetFoam midsole made from sugarcane provides cushioning. Machine washable for easy care - no special treatment needed. Classic lace-up design with no-show lace option. Merino wool heel liner prevents blisters. FSC-certified rubber outsole for traction. Removable insole made from castor bean oil foam. B Corp certified company committed to sustainability. Perfect for everyday casual wear and light exercise.', 'Allbirds', 'Clothing', 'Shoes', ARRAY['sustainable', 'eco-friendly', 'casual', 'breathable', 'washable'], 98.00, 4.5, 8765, 345, true, false, '{"color": "Kauri Marine", "material": "Eucalyptus Tree Fiber", "carbon_footprint_kg": 7.6, "machine_washable": true, "fit": "True to Size"}'::jsonb, products.generate_random_embedding(1536)),

('The North Face ThermoBall Eco Jacket', 'Synthetic insulation jacket using recycled materials. ThermoBall Eco insulation made from post-consumer recycled content. Lightweight warmth continues insulating even when wet. Packable design stuffs into internal pocket for travel. Water-resistant ripstop shell sheds light precipitation. Secure-zip hand pockets and internal chest pocket. Elastic binding at cuffs and hem seals in warmth. Standard fit allows layering flexibility. Available in multiple colors for men and women. Ideal as midlayer or standalone in mild cold. Part of North Face commitment to sustainability.', 'The North Face', 'Clothing', 'Jackets', ARRAY['insulated', 'packable', 'sustainable', 'recycled', 'lightweight'], 220.00, 4.6, 4567, 189, true, false, '{"color": "TNF Black", "material": "Recycled Ripstop", "insulation": "ThermoBall Eco", "packable": true, "water_resistant": true}'::jsonb, products.generate_random_embedding(1536)),

('Theragun Prime Percussive Massage Device', 'Professional-grade percussive therapy device for muscle recovery and pain relief. QuietForce Technology delivers powerful deep muscle treatment with minimal noise. Ergonomic multi-grip allows easy reach of all muscle groups. Four built-in routines guided by Therabody app. 5 speed settings from 1750 to 2400 PPM. 120-minute battery life with fast charging. Smart app integration tracks usage and provides personalized routines. Includes 4 attachments: dampener, standard ball, thumb, and cone. Helps reduce muscle tension, soreness, and improve flexibility. Used by professional athletes and trainers worldwide. 2-year warranty included.', 'Therabody', 'Sports', 'Fitness', ARRAY['massage', 'recovery', 'muscle', 'percussion', 'therapy'], 299.00, 4.7, 5678, 123, true, true, '{"speed_settings": 5, "max_rpm": 2400, "battery_life_minutes": 120, "attachments": 4, "weight_lbs": 2.2}'::jsonb, products.generate_random_embedding(1536)),

('Bowflex SelectTech 552 Adjustable Dumbbells', 'Space-saving adjustable dumbbells replace 15 sets of weights. Dial system adjusts from 5 to 52.5 lbs in 2.5 lb increments up to 25 lbs. Smooth transition between weights with simple dial turn. Durable molding around metal plates for safe storage. Compact design fits in corner of room or closet. Works with optional Bowflex stand sold separately. Free Bowflex JRNY app membership with purchase. Two-year warranty on weight plates and parts. Perfect for home gym with limited space. Sold as pair for complete workout capability.', 'Bowflex', 'Sports', 'Fitness', ARRAY['dumbbells', 'adjustable', 'home-gym', 'strength-training', 'space-saving'], 429.00, 4.8, 23456, 78, true, true, '{"weight_range_lbs": "5-52.5", "increments_lbs": 2.5, "adjustments": 15, "warranty_years": 2, "sold_as": "Pair"}'::jsonb, products.generate_random_embedding(1536)),

('Garmin Forerunner 265 GPS Running Watch', 'Advanced GPS running watch with vibrant AMOLED display. Training readiness score indicates if you''re ready for another hard workout. Morning report summarizes sleep, HRV, and weather. Race predictor estimates finish times for 5K, 10K, half, and full marathon. Training status and load features help prevent overtraining. Music storage for 500 songs plays through Bluetooth headphones. Body Battery energy monitoring shows energy reserves throughout day. Up to 13 days battery in smartwatch mode, 20 hours in GPS mode. Connect IQ store offers additional apps, widgets, and watch faces. Advanced running dynamics with compatible accessories.', 'Garmin', 'Sports', 'Fitness', ARRAY['GPS', 'running', 'smartwatch', 'training', 'AMOLED'], 449.99, 4.8, 3456, 89, true, true, '{"display": "AMOLED", "battery_gps_hours": 20, "battery_smartwatch_days": 13, "music_storage_songs": 500, "water_rating": "5 ATM"}'::jsonb, products.generate_random_embedding(1536)),

('Manduka PRO Yoga Mat', 'Professional-grade yoga mat trusted by teachers and studios worldwide. Dense 6mm cushioning provides joint protection on hard floors. Closed-cell surface prevents sweat absorption and bacterial buildup. Lifetime guarantee backs exceptional durability and quality. High-density PVC resists wear and maintains grip for years. Ideal for all yoga styles from gentle to power practices. 71-inch standard length accommodates most practitioners. Heavy weight keeps mat firmly in place during practice. Oeko-Tex certified free from harmful chemicals. Break-in period creates superior grip over time. Made in Germany with environmentally conscious manufacturing.', 'Manduka', 'Sports', 'Fitness', ARRAY['yoga', 'mat', 'professional', 'durable', 'non-slip'], 120.00, 4.7, 6789, 234, true, false, '{"thickness_mm": 6, "length_inches": 71, "width_inches": 26, "material": "PVC", "warranty": "Lifetime"}'::jsonb, products.generate_random_embedding(1536)),

('Yeti Rambler 36oz Bottle with Chug Cap', 'Rugged stainless steel insulated bottle keeps drinks cold all day. Double-wall vacuum insulation prevents condensation and maintains temperature. Duracoat color won''t fade, peel, or crack. Over-the-nose design drinks easily without removing cap. TripleHaul cap handle makes one-handed carrying effortless. Fits in most car cup holders and bike cages. Dishwasher safe for easy cleaning. BPA-free construction safe for hot and cold beverages. No Sweat exterior keeps hands dry. Perfect for hiking, camping, gym, or everyday hydration.', 'Yeti', 'Sports', 'Outdoor', ARRAY['water-bottle', 'insulated', 'stainless-steel', 'outdoor', 'durable'], 50.00, 4.8, 12345, 567, true, false, '{"capacity_oz": 36, "material": "18/8 Stainless Steel", "insulation": "Double-Wall Vacuum", "dishwasher_safe": true, "bpa_free": true}'::jsonb, products.generate_random_embedding(1536)),

('Coleman Sundome 4-Person Camping Tent', 'Easy-setup dome tent perfect for weekend camping trips. WeatherTec system with patented welded floors and inverted seams keeps water out. Snag-free continuous pole sleeves enable quick 10-minute setup. Large windows and ground vents provide cross-ventilation. Electrical access port allows power cord entry from outside. Interior storage pockets organize small items. Removable rainfly for stargazing on clear nights. Fits one queen air mattress with room to spare. Included carry bag with compression straps for compact storage. 1-year limited warranty. Great value for casual campers.', 'Coleman', 'Sports', 'Outdoor', ARRAY['camping', 'tent', 'outdoor', 'family', 'waterproof'], 79.99, 4.4, 34567, 345, true, false, '{"capacity_persons": 4, "setup_time_minutes": 10, "peak_height_ft": 4.92, "floor_area_sqft": 63, "packed_size_inches": "24x7"}'::jsonb, products.generate_random_embedding(1536)),

('Atomic Habits by James Clear', 'New York Times bestseller on building good habits and breaking bad ones. Reveals practical strategies for forming habits that stick based on biology, psychology, and neuroscience. Learn the Four Laws of Behavior Change: make it obvious, attractive, easy, and satisfying. Discover why tiny changes deliver remarkable results over time. Real-world examples from Olympic athletes, artists, and business leaders. Actionable framework you can apply immediately. Over 10 million copies sold worldwide. Recommended by successful people across industries. Perfect for anyone wanting to improve their daily routines and long-term outcomes.', 'Avery', 'Books', 'Non-Fiction', ARRAY['self-help', 'habits', 'productivity', 'psychology', 'bestseller'], 18.99, 4.8, 123456, 890, true, true, '{"author": "James Clear", "pages": 320, "format": "Hardcover", "publisher": "Avery", "publication_year": 2018}'::jsonb, products.generate_random_embedding(1536)),

('Project Hail Mary by Andy Weir', 'From the author of The Martian comes another thrilling space survival story. Astronaut Ryland Grace wakes up alone on a spacecraft with no memory. He must save Earth from extinction and figure out how he got there. Mind-bending science woven into gripping adventure narrative. Perfect blend of hard science fiction and humor. Explores first contact, friendship, and the limits of human determination. Winner of multiple science fiction awards. Now a major motion picture starring Ryan Gosling. Ideal for fans of The Martian who want another page-turning adventure.', 'Ballantine Books', 'Books', 'Fiction', ARRAY['science-fiction', 'thriller', 'space', 'adventure', 'bestseller'], 16.99, 4.9, 89012, 567, true, true, '{"author": "Andy Weir", "pages": 496, "format": "Paperback", "publisher": "Ballantine Books", "publication_year": 2021}'::jsonb, products.generate_random_embedding(1536)),

('The Pragmatic Programmer 20th Anniversary Edition', 'Classic software development book completely rewritten for modern era. Covers source control, testing, debugging, automation, and team collaboration. Timeless advice on becoming more effective programmer regardless of language or framework. New topics include concurrency, domain languages, and meta-programming. 100 practical tips for career-long improvement. Exercises and challenges encourage hands-on learning. Essential reading for new developers and experienced professionals alike. Referenced by engineering teams at top technology companies. Learn principles that transcend specific technologies and remain relevant decade after decade.', 'Addison-Wesley', 'Books', 'Technical', ARRAY['programming', 'software-development', 'career', 'best-practices', 'classic'], 49.99, 4.8, 5678, 234, true, false, '{"author": "David Thomas, Andrew Hunt", "pages": 352, "format": "Hardcover", "publisher": "Addison-Wesley", "publication_year": 2019}'::jsonb, products.generate_random_embedding(1536)),

('Designing Data-Intensive Applications', 'Essential guide to building reliable and maintainable data systems. Covers databases, message queues, stream processing, and distributed systems. Deep dive into consistency, consensus, and fault tolerance. Compares different database technologies and when to use each. Real-world case studies from internet-scale companies. Explains CAP theorem, ACID, and eventual consistency clearly. Perfect for software engineers working with data at scale. Highly technical yet accessible writing style. Considered definitive reference for data engineering. Second most recommended book in software engineering communities.', 'O''Reilly Media', 'Books', 'Technical', ARRAY['data-engineering', 'databases', 'distributed-systems', 'architecture', 'reference'], 44.99, 4.9, 4567, 178, true, true, '{"author": "Martin Kleppmann", "pages": 611, "format": "Paperback", "publisher": "O''Reilly Media", "publication_year": 2017}'::jsonb, products.generate_random_embedding(1536)),

('Sapiens: A Brief History of Humankind', 'Groundbreaking exploration of human history from Stone Age to present. How did Homo sapiens come to dominate the planet? Examines cognitive, agricultural, and scientific revolutions. Challenges conventional assumptions about progress and happiness. Synthesizes history, biology, and economics into compelling narrative. Translated into over 60 languages with 25 million copies sold. Recommended by Barack Obama, Bill Gates, and Mark Zuckerberg. Thought-provoking perspectives on where humanity might go next. Perfect for curious minds wanting big-picture understanding of human story.', 'Harper Perennial', 'Books', 'Non-Fiction', ARRAY['history', 'anthropology', 'science', 'bestseller', 'thought-provoking'], 17.99, 4.6, 78901, 456, true, false, '{"author": "Yuval Noah Harari", "pages": 464, "format": "Paperback", "publisher": "Harper Perennial", "publication_year": 2015}'::jsonb, products.generate_random_embedding(1536));

-- Verify data load
DO $$
DECLARE
    product_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO product_count FROM products.items;
    RAISE NOTICE 'Loaded % products into products.items', product_count;
    RAISE NOTICE 'Categories: Electronics, Home & Garden, Clothing, Sports, Books';
END $$;
